name: Deploy Laravel App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Namecheap Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Connect to Server via SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }} # 66.29.153.80
          username: ${{ secrets.SSH_USER }} # huzakdhg
          key: ${{ secrets.SSH_PRIVATE_KEY }} # contents of your private key
          port: ${{ secrets.SSH_PORT }} # 21098
          script: |
            cd /home/huzakdhg/techno_commerce

            echo "Pulling latest code from GitHub..."
            git pull origin master

            echo "Installing Composer dependencies..."
            /opt/cpanel/ea-php82/root/usr/bin/php /opt/cpanel/composer/bin/composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "Running migrations..."
            /opt/cpanel/ea-php82/root/usr/bin/php artisan migrate --force

            echo "Seeding database..."
            /opt/cpanel/ea-php82/root/usr/bin/php artisan db:seed --force

            echo "Clearing cache and rebuilding config..."
            /opt/cpanel/ea-php82/root/usr/bin/php artisan config:clear
            /opt/cpanel/ea-php82/root/usr/bin/php artisan cache:clear
            /opt/cpanel/ea-php82/root/usr/bin/php artisan config:cache
            /opt/cpanel/ea-php82/root/usr/bin/php artisan route:cache
            /opt/cpanel/ea-php82/root/usr/bin/php artisan view:cache

            echo "Restarting queue workers..."
            /opt/cpanel/ea-php82/root/usr/bin/php artisan queue:restart

            echo "✅ Deployment completed successfully."
