name: Deploy Laravel App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Namecheap Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Server via SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 66.29.153.80
          username: huzakdhg
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 21098
          script: |
            cd /home/huzakdhg/techno_commerce

            echo "Pulling latest code from GitHub..."
            git pull origin master

            echo "Installing Composer dependencies..."
            /usr/local/bin/php /opt/cpanel/composer/bin/composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "Running migrations..."
            /usr/local/bin/php artisan migrate --force

            echo "Seeding database..."
            /usr/local/bin/php artisan db:seed --force

            echo "Clearing cache and config..."
            /usr/local/bin/php artisan config:clear
            /usr/local/bin/php artisan cache:clear
            /usr/local/bin/php artisan config:cache
            /usr/local/bin/php artisan route:cache
            /usr/local/bin/php artisan view:cache

            echo "Restarting queue workers..."
            /usr/local/bin/php artisan queue:restart

            echo "Deployment completed."
